//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemittanceOperation.GCCServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CashTxnResponse", Namespace="http://schemas.datacontract.org/2004/07/GCCService.ResponseClasses")]
    [System.SerializableAttribute()]
    public partial class CashTxnResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountToPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountToPayInWordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveCountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveCurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverFourthNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverNationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendCountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFourthNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIDExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIDPlaceOfIssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIDTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIDTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIncomeSourceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIncomeSourceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderOccupationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderOccupationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmountToPay {
            get {
                return this.AmountToPayField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountToPayField, value) != true)) {
                    this.AmountToPayField = value;
                    this.RaisePropertyChanged("AmountToPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmountToPayInWords {
            get {
                return this.AmountToPayInWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountToPayInWordsField, value) != true)) {
                    this.AmountToPayInWordsField = value;
                    this.RaisePropertyChanged("AmountToPayInWords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurposeCode {
            get {
                return this.PurposeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeCodeField, value) != true)) {
                    this.PurposeCodeField = value;
                    this.RaisePropertyChanged("PurposeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurposeName {
            get {
                return this.PurposeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeNameField, value) != true)) {
                    this.PurposeNameField = value;
                    this.RaisePropertyChanged("PurposeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveCountryCode {
            get {
                return this.ReceiveCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveCountryCodeField, value) != true)) {
                    this.ReceiveCountryCodeField = value;
                    this.RaisePropertyChanged("ReceiveCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveCountryName {
            get {
                return this.ReceiveCountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveCountryNameField, value) != true)) {
                    this.ReceiveCountryNameField = value;
                    this.RaisePropertyChanged("ReceiveCountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveCurrencyCode {
            get {
                return this.ReceiveCurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveCurrencyCodeField, value) != true)) {
                    this.ReceiveCurrencyCodeField = value;
                    this.RaisePropertyChanged("ReceiveCurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverAddress {
            get {
                return this.ReceiverAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverAddressField, value) != true)) {
                    this.ReceiverAddressField = value;
                    this.RaisePropertyChanged("ReceiverAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverCity {
            get {
                return this.ReceiverCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverCityField, value) != true)) {
                    this.ReceiverCityField = value;
                    this.RaisePropertyChanged("ReceiverCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverContactNo {
            get {
                return this.ReceiverContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverContactNoField, value) != true)) {
                    this.ReceiverContactNoField = value;
                    this.RaisePropertyChanged("ReceiverContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverFirstName {
            get {
                return this.ReceiverFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverFirstNameField, value) != true)) {
                    this.ReceiverFirstNameField = value;
                    this.RaisePropertyChanged("ReceiverFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverFourthName {
            get {
                return this.ReceiverFourthNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverFourthNameField, value) != true)) {
                    this.ReceiverFourthNameField = value;
                    this.RaisePropertyChanged("ReceiverFourthName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverLastName {
            get {
                return this.ReceiverLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverLastNameField, value) != true)) {
                    this.ReceiverLastNameField = value;
                    this.RaisePropertyChanged("ReceiverLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverMiddleName {
            get {
                return this.ReceiverMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverMiddleNameField, value) != true)) {
                    this.ReceiverMiddleNameField = value;
                    this.RaisePropertyChanged("ReceiverMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverNationality {
            get {
                return this.ReceiverNationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverNationalityField, value) != true)) {
                    this.ReceiverNationalityField = value;
                    this.RaisePropertyChanged("ReceiverNationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendCountryCode {
            get {
                return this.SendCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SendCountryCodeField, value) != true)) {
                    this.SendCountryCodeField = value;
                    this.RaisePropertyChanged("SendCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendCountryName {
            get {
                return this.SendCountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SendCountryNameField, value) != true)) {
                    this.SendCountryNameField = value;
                    this.RaisePropertyChanged("SendCountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderAddress {
            get {
                return this.SenderAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderAddressField, value) != true)) {
                    this.SenderAddressField = value;
                    this.RaisePropertyChanged("SenderAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderCity {
            get {
                return this.SenderCityField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderCityField, value) != true)) {
                    this.SenderCityField = value;
                    this.RaisePropertyChanged("SenderCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderContactNo {
            get {
                return this.SenderContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderContactNoField, value) != true)) {
                    this.SenderContactNoField = value;
                    this.RaisePropertyChanged("SenderContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFirstName {
            get {
                return this.SenderFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFirstNameField, value) != true)) {
                    this.SenderFirstNameField = value;
                    this.RaisePropertyChanged("SenderFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFourthName {
            get {
                return this.SenderFourthNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFourthNameField, value) != true)) {
                    this.SenderFourthNameField = value;
                    this.RaisePropertyChanged("SenderFourthName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIDExpiryDate {
            get {
                return this.SenderIDExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDExpiryDateField, value) != true)) {
                    this.SenderIDExpiryDateField = value;
                    this.RaisePropertyChanged("SenderIDExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIDNumber {
            get {
                return this.SenderIDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDNumberField, value) != true)) {
                    this.SenderIDNumberField = value;
                    this.RaisePropertyChanged("SenderIDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIDPlaceOfIssue {
            get {
                return this.SenderIDPlaceOfIssueField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDPlaceOfIssueField, value) != true)) {
                    this.SenderIDPlaceOfIssueField = value;
                    this.RaisePropertyChanged("SenderIDPlaceOfIssue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIDTypeCode {
            get {
                return this.SenderIDTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDTypeCodeField, value) != true)) {
                    this.SenderIDTypeCodeField = value;
                    this.RaisePropertyChanged("SenderIDTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIDTypeName {
            get {
                return this.SenderIDTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDTypeNameField, value) != true)) {
                    this.SenderIDTypeNameField = value;
                    this.RaisePropertyChanged("SenderIDTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIncomeSourceCode {
            get {
                return this.SenderIncomeSourceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIncomeSourceCodeField, value) != true)) {
                    this.SenderIncomeSourceCodeField = value;
                    this.RaisePropertyChanged("SenderIncomeSourceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIncomeSourceName {
            get {
                return this.SenderIncomeSourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIncomeSourceNameField, value) != true)) {
                    this.SenderIncomeSourceNameField = value;
                    this.RaisePropertyChanged("SenderIncomeSourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderLastName {
            get {
                return this.SenderLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderLastNameField, value) != true)) {
                    this.SenderLastNameField = value;
                    this.RaisePropertyChanged("SenderLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderMiddleName {
            get {
                return this.SenderMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderMiddleNameField, value) != true)) {
                    this.SenderMiddleNameField = value;
                    this.RaisePropertyChanged("SenderMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderNationality {
            get {
                return this.SenderNationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNationalityField, value) != true)) {
                    this.SenderNationalityField = value;
                    this.RaisePropertyChanged("SenderNationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderOccupationCode {
            get {
                return this.SenderOccupationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderOccupationCodeField, value) != true)) {
                    this.SenderOccupationCodeField = value;
                    this.RaisePropertyChanged("SenderOccupationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderOccupationName {
            get {
                return this.SenderOccupationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderOccupationNameField, value) != true)) {
                    this.SenderOccupationNameField = value;
                    this.RaisePropertyChanged("SenderOccupationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessfulField, value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDateField, value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNo {
            get {
                return this.TransactionNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNoField, value) != true)) {
                    this.TransactionNoField = value;
                    this.RaisePropertyChanged("TransactionNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayTranResponses", Namespace="http://schemas.datacontract.org/2004/07/GCCService.ResponseClasses")]
    [System.SerializableAttribute()]
    public partial class PayTranResponses : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountToPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveCountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveCurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmountToPay {
            get {
                return this.AmountToPayField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountToPayField, value) != true)) {
                    this.AmountToPayField = value;
                    this.RaisePropertyChanged("AmountToPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveCountryName {
            get {
                return this.ReceiveCountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveCountryNameField, value) != true)) {
                    this.ReceiveCountryNameField = value;
                    this.RaisePropertyChanged("ReceiveCountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveCurrencyCode {
            get {
                return this.ReceiveCurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveCurrencyCodeField, value) != true)) {
                    this.ReceiveCurrencyCodeField = value;
                    this.RaisePropertyChanged("ReceiveCurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDateField, value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNo {
            get {
                return this.TransactionNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNoField, value) != true)) {
                    this.TransactionNoField = value;
                    this.RaisePropertyChanged("TransactionNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankDepositResponse", Namespace="http://schemas.datacontract.org/2004/07/GCCService.ResponseClasses")]
    [System.SerializableAttribute()]
    public partial class BankDepositResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RemittanceOperation.GCCServiceClient.DtResult[] dsTransactionListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessfulField, value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RemittanceOperation.GCCServiceClient.DtResult[] dsTransactionList {
            get {
                return this.dsTransactionListField;
            }
            set {
                if ((object.ReferenceEquals(this.dsTransactionListField, value) != true)) {
                    this.dsTransactionListField = value;
                    this.RaisePropertyChanged("dsTransactionList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtResult", Namespace="http://schemas.datacontract.org/2004/07/GCCService.ResponseClasses")]
    [System.SerializableAttribute()]
    public partial class DtResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankBranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankBranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PayinAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayinCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayinCountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayinCurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PayoutAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutCityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutCountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutCurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutLocationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutLocationCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutLocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverFourthNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverNationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFourthNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SenderIDExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIDPlaceOfIssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIDTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIncomeSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderOccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValueDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountNo {
            get {
                return this.BankAccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountNoField, value) != true)) {
                    this.BankAccountNoField = value;
                    this.RaisePropertyChanged("BankAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAddress {
            get {
                return this.BankAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAddressField, value) != true)) {
                    this.BankAddressField = value;
                    this.RaisePropertyChanged("BankAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankBranchCode {
            get {
                return this.BankBranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankBranchCodeField, value) != true)) {
                    this.BankBranchCodeField = value;
                    this.RaisePropertyChanged("BankBranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankBranchName {
            get {
                return this.BankBranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankBranchNameField, value) != true)) {
                    this.BankBranchNameField = value;
                    this.RaisePropertyChanged("BankBranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCode {
            get {
                return this.BankCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankCodeField, value) != true)) {
                    this.BankCodeField = value;
                    this.RaisePropertyChanged("BankCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCountry {
            get {
                return this.BankCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.BankCountryField, value) != true)) {
                    this.BankCountryField = value;
                    this.RaisePropertyChanged("BankCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankZipCode {
            get {
                return this.BankZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankZipCodeField, value) != true)) {
                    this.BankZipCodeField = value;
                    this.RaisePropertyChanged("BankZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ExchangeRate {
            get {
                return this.ExchangeRateField;
            }
            set {
                if ((this.ExchangeRateField.Equals(value) != true)) {
                    this.ExchangeRateField = value;
                    this.RaisePropertyChanged("ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PayinAmount {
            get {
                return this.PayinAmountField;
            }
            set {
                if ((this.PayinAmountField.Equals(value) != true)) {
                    this.PayinAmountField = value;
                    this.RaisePropertyChanged("PayinAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayinCountryCode {
            get {
                return this.PayinCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayinCountryCodeField, value) != true)) {
                    this.PayinCountryCodeField = value;
                    this.RaisePropertyChanged("PayinCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayinCountryName {
            get {
                return this.PayinCountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PayinCountryNameField, value) != true)) {
                    this.PayinCountryNameField = value;
                    this.RaisePropertyChanged("PayinCountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayinCurrencyCode {
            get {
                return this.PayinCurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayinCurrencyCodeField, value) != true)) {
                    this.PayinCurrencyCodeField = value;
                    this.RaisePropertyChanged("PayinCurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMode {
            get {
                return this.PaymentModeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentModeField, value) != true)) {
                    this.PaymentModeField = value;
                    this.RaisePropertyChanged("PaymentMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PayoutAmount {
            get {
                return this.PayoutAmountField;
            }
            set {
                if ((this.PayoutAmountField.Equals(value) != true)) {
                    this.PayoutAmountField = value;
                    this.RaisePropertyChanged("PayoutAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutCityName {
            get {
                return this.PayoutCityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutCityNameField, value) != true)) {
                    this.PayoutCityNameField = value;
                    this.RaisePropertyChanged("PayoutCityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutCountryCode {
            get {
                return this.PayoutCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutCountryCodeField, value) != true)) {
                    this.PayoutCountryCodeField = value;
                    this.RaisePropertyChanged("PayoutCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutCountryName {
            get {
                return this.PayoutCountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutCountryNameField, value) != true)) {
                    this.PayoutCountryNameField = value;
                    this.RaisePropertyChanged("PayoutCountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutCurrencyCode {
            get {
                return this.PayoutCurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutCurrencyCodeField, value) != true)) {
                    this.PayoutCurrencyCodeField = value;
                    this.RaisePropertyChanged("PayoutCurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutLocationCode {
            get {
                return this.PayoutLocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutLocationCodeField, value) != true)) {
                    this.PayoutLocationCodeField = value;
                    this.RaisePropertyChanged("PayoutLocationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutLocationCode2 {
            get {
                return this.PayoutLocationCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutLocationCode2Field, value) != true)) {
                    this.PayoutLocationCode2Field = value;
                    this.RaisePropertyChanged("PayoutLocationCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutLocationName {
            get {
                return this.PayoutLocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutLocationNameField, value) != true)) {
                    this.PayoutLocationNameField = value;
                    this.RaisePropertyChanged("PayoutLocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Purpose {
            get {
                return this.PurposeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeField, value) != true)) {
                    this.PurposeField = value;
                    this.RaisePropertyChanged("Purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverContactNo {
            get {
                return this.ReceiverContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverContactNoField, value) != true)) {
                    this.ReceiverContactNoField = value;
                    this.RaisePropertyChanged("ReceiverContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverFirstName {
            get {
                return this.ReceiverFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverFirstNameField, value) != true)) {
                    this.ReceiverFirstNameField = value;
                    this.RaisePropertyChanged("ReceiverFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverFourthName {
            get {
                return this.ReceiverFourthNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverFourthNameField, value) != true)) {
                    this.ReceiverFourthNameField = value;
                    this.RaisePropertyChanged("ReceiverFourthName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverFullName {
            get {
                return this.ReceiverFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverFullNameField, value) != true)) {
                    this.ReceiverFullNameField = value;
                    this.RaisePropertyChanged("ReceiverFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverLastName {
            get {
                return this.ReceiverLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverLastNameField, value) != true)) {
                    this.ReceiverLastNameField = value;
                    this.RaisePropertyChanged("ReceiverLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverMiddleName {
            get {
                return this.ReceiverMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverMiddleNameField, value) != true)) {
                    this.ReceiverMiddleNameField = value;
                    this.RaisePropertyChanged("ReceiverMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverNationality {
            get {
                return this.ReceiverNationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverNationalityField, value) != true)) {
                    this.ReceiverNationalityField = value;
                    this.RaisePropertyChanged("ReceiverNationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderAddress {
            get {
                return this.SenderAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderAddressField, value) != true)) {
                    this.SenderAddressField = value;
                    this.RaisePropertyChanged("SenderAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderEmail {
            get {
                return this.SenderEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderEmailField, value) != true)) {
                    this.SenderEmailField = value;
                    this.RaisePropertyChanged("SenderEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFirstName {
            get {
                return this.SenderFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFirstNameField, value) != true)) {
                    this.SenderFirstNameField = value;
                    this.RaisePropertyChanged("SenderFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFourthName {
            get {
                return this.SenderFourthNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFourthNameField, value) != true)) {
                    this.SenderFourthNameField = value;
                    this.RaisePropertyChanged("SenderFourthName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFullName {
            get {
                return this.SenderFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFullNameField, value) != true)) {
                    this.SenderFullNameField = value;
                    this.RaisePropertyChanged("SenderFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SenderIDExpiryDate {
            get {
                return this.SenderIDExpiryDateField;
            }
            set {
                if ((this.SenderIDExpiryDateField.Equals(value) != true)) {
                    this.SenderIDExpiryDateField = value;
                    this.RaisePropertyChanged("SenderIDExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIDNumber {
            get {
                return this.SenderIDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDNumberField, value) != true)) {
                    this.SenderIDNumberField = value;
                    this.RaisePropertyChanged("SenderIDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIDPlaceOfIssue {
            get {
                return this.SenderIDPlaceOfIssueField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDPlaceOfIssueField, value) != true)) {
                    this.SenderIDPlaceOfIssueField = value;
                    this.RaisePropertyChanged("SenderIDPlaceOfIssue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIDType {
            get {
                return this.SenderIDTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDTypeField, value) != true)) {
                    this.SenderIDTypeField = value;
                    this.RaisePropertyChanged("SenderIDType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderIncomeSource {
            get {
                return this.SenderIncomeSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIncomeSourceField, value) != true)) {
                    this.SenderIncomeSourceField = value;
                    this.RaisePropertyChanged("SenderIncomeSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderLastName {
            get {
                return this.SenderLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderLastNameField, value) != true)) {
                    this.SenderLastNameField = value;
                    this.RaisePropertyChanged("SenderLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderMiddleName {
            get {
                return this.SenderMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderMiddleNameField, value) != true)) {
                    this.SenderMiddleNameField = value;
                    this.RaisePropertyChanged("SenderMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderNationality {
            get {
                return this.SenderNationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNationalityField, value) != true)) {
                    this.SenderNationalityField = value;
                    this.RaisePropertyChanged("SenderNationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderOccupation {
            get {
                return this.SenderOccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderOccupationField, value) != true)) {
                    this.SenderOccupationField = value;
                    this.RaisePropertyChanged("SenderOccupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderZipCode {
            get {
                return this.SenderZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderZipCodeField, value) != true)) {
                    this.SenderZipCodeField = value;
                    this.RaisePropertyChanged("SenderZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentDate {
            get {
                return this.SentDateField;
            }
            set {
                if ((this.SentDateField.Equals(value) != true)) {
                    this.SentDateField = value;
                    this.RaisePropertyChanged("SentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNo {
            get {
                return this.TransactionNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNoField, value) != true)) {
                    this.TransactionNoField = value;
                    this.RaisePropertyChanged("TransactionNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValueDate {
            get {
                return this.ValueDateField;
            }
            set {
                if ((this.ValueDateField.Equals(value) != true)) {
                    this.ValueDateField = value;
                    this.RaisePropertyChanged("ValueDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTransResponse", Namespace="http://schemas.datacontract.org/2004/07/GCCService.ResponseClasses")]
    [System.SerializableAttribute()]
    public partial class ProcessTransResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AmountToPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountToPayInWordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveCountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveCurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float AmountToPay {
            get {
                return this.AmountToPayField;
            }
            set {
                if ((this.AmountToPayField.Equals(value) != true)) {
                    this.AmountToPayField = value;
                    this.RaisePropertyChanged("AmountToPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmountToPayInWords {
            get {
                return this.AmountToPayInWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountToPayInWordsField, value) != true)) {
                    this.AmountToPayInWordsField = value;
                    this.RaisePropertyChanged("AmountToPayInWords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveCountryName {
            get {
                return this.ReceiveCountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveCountryNameField, value) != true)) {
                    this.ReceiveCountryNameField = value;
                    this.RaisePropertyChanged("ReceiveCountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveCurrencyCode {
            get {
                return this.ReceiveCurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveCurrencyCodeField, value) != true)) {
                    this.ReceiveCurrencyCodeField = value;
                    this.RaisePropertyChanged("ReceiveCurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendCountryCode {
            get {
                return this.SendCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SendCountryCodeField, value) != true)) {
                    this.SendCountryCodeField = value;
                    this.RaisePropertyChanged("SendCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessfulField, value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDateField, value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNo {
            get {
                return this.TransactionNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNoField, value) != true)) {
                    this.TransactionNoField = value;
                    this.RaisePropertyChanged("TransactionNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateBankDepositResponse", Namespace="http://schemas.datacontract.org/2004/07/GCCService.ResponseClasses")]
    [System.SerializableAttribute()]
    public partial class UpdateBankDepositResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessfulField, value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNo {
            get {
                return this.TransactionNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNoField, value) != true)) {
                    this.TransactionNoField = value;
                    this.RaisePropertyChanged("TransactionNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/GCCService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GCCServiceClient.IGCCService")]
    public interface IGCCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/DisplayTransaction", ReplyAction="http://tempuri.org/IGCCService/DisplayTransactionResponse")]
        RemittanceOperation.GCCServiceClient.CashTxnResponse DisplayTransaction(string securityCode, string TransactionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/DisplayTransaction", ReplyAction="http://tempuri.org/IGCCService/DisplayTransactionResponse")]
        System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.CashTxnResponse> DisplayTransactionAsync(string securityCode, string TransactionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/PayTransaction", ReplyAction="http://tempuri.org/IGCCService/PayTransactionResponse")]
        RemittanceOperation.GCCServiceClient.PayTranResponses PayTransaction(string securityCode, string TransactionNo, string ReceiverIDType, string ReceiverIDNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/PayTransaction", ReplyAction="http://tempuri.org/IGCCService/PayTransactionResponse")]
        System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.PayTranResponses> PayTransactionAsync(string securityCode, string TransactionNo, string ReceiverIDType, string ReceiverIDNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/BankDepositTxn", ReplyAction="http://tempuri.org/IGCCService/BankDepositTxnResponse")]
        RemittanceOperation.GCCServiceClient.BankDepositResponse BankDepositTxn(string securityCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/BankDepositTxn", ReplyAction="http://tempuri.org/IGCCService/BankDepositTxnResponse")]
        System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.BankDepositResponse> BankDepositTxnAsync(string securityCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/ProcessBankDepositTxn", ReplyAction="http://tempuri.org/IGCCService/ProcessBankDepositTxnResponse")]
        RemittanceOperation.GCCServiceClient.ProcessTransResponse ProcessBankDepositTxn(string securityCode, string TransactionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/ProcessBankDepositTxn", ReplyAction="http://tempuri.org/IGCCService/ProcessBankDepositTxnResponse")]
        System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.ProcessTransResponse> ProcessBankDepositTxnAsync(string securityCode, string TransactionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/UpdateBankDepositTxnToPaid", ReplyAction="http://tempuri.org/IGCCService/UpdateBankDepositTxnToPaidResponse")]
        RemittanceOperation.GCCServiceClient.UpdateBankDepositResponse UpdateBankDepositTxnToPaid(string securityCode, string TransactionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/UpdateBankDepositTxnToPaid", ReplyAction="http://tempuri.org/IGCCService/UpdateBankDepositTxnToPaidResponse")]
        System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.UpdateBankDepositResponse> UpdateBankDepositTxnToPaidAsync(string securityCode, string TransactionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGCCService/GetDataUsingDataContractResponse")]
        RemittanceOperation.GCCServiceClient.CompositeType GetDataUsingDataContract(RemittanceOperation.GCCServiceClient.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGCCService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGCCService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.CompositeType> GetDataUsingDataContractAsync(RemittanceOperation.GCCServiceClient.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGCCServiceChannel : RemittanceOperation.GCCServiceClient.IGCCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GCCServiceClient : System.ServiceModel.ClientBase<RemittanceOperation.GCCServiceClient.IGCCService>, RemittanceOperation.GCCServiceClient.IGCCService {
        
        public GCCServiceClient() {
        }
        
        public GCCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GCCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GCCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GCCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RemittanceOperation.GCCServiceClient.CashTxnResponse DisplayTransaction(string securityCode, string TransactionNo) {
            return base.Channel.DisplayTransaction(securityCode, TransactionNo);
        }
        
        public System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.CashTxnResponse> DisplayTransactionAsync(string securityCode, string TransactionNo) {
            return base.Channel.DisplayTransactionAsync(securityCode, TransactionNo);
        }
        
        public RemittanceOperation.GCCServiceClient.PayTranResponses PayTransaction(string securityCode, string TransactionNo, string ReceiverIDType, string ReceiverIDNumber) {
            return base.Channel.PayTransaction(securityCode, TransactionNo, ReceiverIDType, ReceiverIDNumber);
        }
        
        public System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.PayTranResponses> PayTransactionAsync(string securityCode, string TransactionNo, string ReceiverIDType, string ReceiverIDNumber) {
            return base.Channel.PayTransactionAsync(securityCode, TransactionNo, ReceiverIDType, ReceiverIDNumber);
        }
        
        public RemittanceOperation.GCCServiceClient.BankDepositResponse BankDepositTxn(string securityCode) {
            return base.Channel.BankDepositTxn(securityCode);
        }
        
        public System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.BankDepositResponse> BankDepositTxnAsync(string securityCode) {
            return base.Channel.BankDepositTxnAsync(securityCode);
        }
        
        public RemittanceOperation.GCCServiceClient.ProcessTransResponse ProcessBankDepositTxn(string securityCode, string TransactionNo) {
            return base.Channel.ProcessBankDepositTxn(securityCode, TransactionNo);
        }
        
        public System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.ProcessTransResponse> ProcessBankDepositTxnAsync(string securityCode, string TransactionNo) {
            return base.Channel.ProcessBankDepositTxnAsync(securityCode, TransactionNo);
        }
        
        public RemittanceOperation.GCCServiceClient.UpdateBankDepositResponse UpdateBankDepositTxnToPaid(string securityCode, string TransactionNo) {
            return base.Channel.UpdateBankDepositTxnToPaid(securityCode, TransactionNo);
        }
        
        public System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.UpdateBankDepositResponse> UpdateBankDepositTxnToPaidAsync(string securityCode, string TransactionNo) {
            return base.Channel.UpdateBankDepositTxnToPaidAsync(securityCode, TransactionNo);
        }
        
        public RemittanceOperation.GCCServiceClient.CompositeType GetDataUsingDataContract(RemittanceOperation.GCCServiceClient.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<RemittanceOperation.GCCServiceClient.CompositeType> GetDataUsingDataContractAsync(RemittanceOperation.GCCServiceClient.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
